{
 "title": "HANU Ceph Cluster",
 "description": "Ceph cluster overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "taco_cluster", "query": "label_values(up, taco_cluster)" }
  ]
 },
 "panels": [
  {
   "title": "Health Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_health_status{taco_cluster=~'$taco_cluster'}"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "All",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_osd_metadata{taco_cluster=~\"$taco_cluster\"})",
     "legendFormat": "All",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "In",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osds_in{taco_cluster=~\"$taco_cluster\"})",
     "legendFormat": "In",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Out",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in{taco_cluster=~\"$taco_cluster\"} == bool 0)",
     "legendFormat": "Out",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{taco_cluster=~\"$taco_cluster\"})",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "crit": 2,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{taco_cluster=~\"$taco_cluster\"} == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "Capacity used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes_used{taco_cluster=~\"$taco_cluster\"})/sum(ceph_osd_stat_bytes{taco_cluster=~\"$taco_cluster\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "PG States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_pg_total", "legendFormat": "Total" },
    { "expr": "ceph_pg_active", "legendFormat": "Active" },
    { "expr": "ceph_pg_total - ceph_pg_active", "legendFormat": "Inactive" },
    { "expr": "ceph_pg_undersized", "legendFormat": "Undersized" },
    { "expr": "ceph_pg_degraded", "legendFormat": "Degraded" },
    { "expr": "ceph_pg_inconsistent", "legendFormat": "Inconsistent" },
    { "expr": "ceph_pg_down", "legendFormat": "Down" }
   ]
  },
  {
   "title": "OSD Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "quantile(0.95, ceph_osd_apply_latency_ms{taco_cluster=~\"$taco_cluster\"})",
     "legendFormat": "Apply Latency P_95"
    },
    {
     "expr": "quantile(0.95, ceph_osd_commit_latency_ms{taco_cluster=~\"$taco_cluster\"})",
     "legendFormat": "Commit Latency P_95"
    },
    {
     "expr": "avg(ceph_osd_apply_latency_ms{taco_cluster=~\"$taco_cluster\"})",
     "legendFormat": "Avg Apply Latency"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{taco_cluster=~\"$taco_cluster\"})",
     "legendFormat": "Avg Commit Latency"
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "In Quorum",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_mon_quorum_status{taco_cluster=~\"$taco_cluster\"})",
     "legendFormat": "In Quorum",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "Total",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mon_quorum_status{taco_cluster=~\"$taco_cluster\"})",
     "legendFormat": "Total",
     "units": "none",
     "valueHandler": "Text Only",
     "warn": 2
    },
    {
     "aggregation": "Last",
     "alias": "MONs out of Quorum",
     "crit": 1.6,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "Never",
     "expr": "count(ceph_mon_quorum_status{taco_cluster=~\"$taco_cluster\"}) / sum(ceph_mon_quorum_status{taco_cluster=~\"$taco_cluster\"})",
     "legendFormat": "MONs out of Quorum",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1.1
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "vonage-status-panel",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Clients",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "ceph_mds_server_handle_client_session{taco_cluster=~\"$taco_cluster\"}",
     "legendFormat": "Clients",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Cluster I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{taco_cluster=~\"$taco_cluster\"}[5m]))",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{taco_cluster=~\"$taco_cluster\"}[5m]))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "In-/Egress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "Bps", "label": " Egress (-) / Ingress (+)" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(ceph_pool_stored{taco_cluster=~\"$taco_cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "OSD Capacity Utilization",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{taco_cluster=~'$taco_cluster'} / ceph_osd_stat_bytes{taco_cluster=~'$taco_cluster'}",
     "legendFormat": "Util (%)"
    }
   ]
  },
  {
   "title": "PGs per OSD",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "ceph_osd_numpg{taco_cluster=~\"$taco_cluster\"}",
     "legendFormat": "#PGs"
    }
   ]
  },
  {
   "title": "Recovery Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ops", "label": "Recovery Ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops[5m]))",
     "legendFormat": "Op/s"
    }
   ]
  }
 ]
}